spring.application.name=licencjat_backend

#DB config
spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}
#spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

#server
server.port=8080

#security
security.jwt.secret-key=b0718a7164fe9766b29bf53072f4a145d75f0ce237659b871421311a6a9225aa
security.jwt.expiration-time=3600000

#Supabase Storage
supabase.url=https://obiamlpnbebhcatcevcs.supabase.co
supabase.key=${SUPABASE_API_KEY}
supabase.bucket=reports-images



